name: 🔧 Build CauseMapster Workflow

on:
  workflow_dispatch:

jobs:
  build:
    name: Construire le logiciel CauseMapster
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Cloner le dépôt
        uses: actions/checkout@v4

      - name: 🔧 Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📦 Installer les dépendances
        run: npm install

      - name: 🧪 Lancer les tests
        run: npm run test || echo "Aucun test trouvé"

      - name: ✅ Fin du build
        run: echo "✅ Build terminé avec succès"
